### ISSUE TITLE
Error: Cannot find module './jestGlobalMocks' from 'setupJest.ts'​​  

### ISSUE THREAD

**Issue by newicz** [bovandersteene/angular-cli-jest-wallaby#1]
After cloning the repo installing dependencies via yarn I got an error in Visual studio code

`​​​0 failing tests, 0 passing​​​​​
​​​​​​​​​​
​​Error: Cannot find module './jestGlobalMocks' from 'setupJest.ts'​​
  at Object.<anonymous> ​src/setupJest.ts:1​
`

**Comment by bovandersteene** [comment]
I've updated the rep to angular 7, can you check again?
